### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by cloudfreexiao** [p308945/MyNetWorkLib#1]
我看 这里的 mysql 测试 用例  没有 执行 存储过程的，
请问  是没支持吗？？？

**Comment by p308945** [comment]
这个暂时没有 存储过程，回头有时间我加上去。

**Comment by cloudfreexiao** [comment]
恩  多谢！！！！
这两天才正常上gmail。。。。

**Comment by p308945** [comment]
最近又有更新，你可以看看，你也可以加我QQ: 895175589，和我交流。

**Comment by cloudfreexiao** [comment]
好的  我找时间 去看看

**Comment by cloudfreexiao** [comment]
QQ已申请
风---自由

2015-11-21 22:26 GMT+08:00 肖津 996442717qqcom@gmail.com:

> 好的  我找时间 去看看
>
